version: '3.3'
services:
    certs:
        container_name: oe-certs 
        image: ghcr.io/mozzy11/certgen-fr:main
        restart: always
        environment:
            - KEYSTORE_PW="kspass"
            - TRUSTSTORE_PW="tspass"
        volumes:
            -  cert-volume:/etc/openelis-global
    database:
        container_name: openelisglobal-database 
        image: postgres:9.5
        ports:
            - "15432:5432"
        restart: always
        env_file:
            - ./volume/database/database.env
        volumes:
              # preserves the database between containers
             - db-data:/var/lib/postgresql/data                
              # files here will run on install
             - ./volume/database/dbInit:/docker-entrypoint-initdb.d
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "clinlims", "-U", "clinlims" ]
            timeout: 45s
            interval: 10s
            retries: 10 
            
    oe.openelis.org:

        container_name: openelisglobal-webapp 
        image: ghcr.io/mozzy11/openelis-global-facility-registry:develop      
        depends_on:
            - database
        ports:
            - "8082:8080"
            - "8443:8443"
        restart: always
        networks:
          default:
              ipv4_address: 172.20.1.121
        environment:
            - DEFAULT_PW=adminADMIN! 
            - TZ=Africa/Nairobi
              # context.xml doesn't seem to be able to pick up environment variables directly, so we are passing them in as CATALINA_OPTS
            - CATALINA_OPTS= -Ddatasource.url=jdbc:postgresql://database:5432/clinlims -Ddatasource.username=clinlims
        volumes:
            -  cert-volume:/etc/openelis-global
            - ./volume/plugins/:/var/lib/openelis-global/plugins
            - ./volume/tomcat/oe_server.xml:/usr/local/tomcat/conf/server.xml
        secrets:
            - source: datasource.password
            - source: common.properties
            
    fhir.openelis.org:
        container_name: external-fhir-api
        image: hapiproject/hapi:latest
        ports:
            - "8081:8080"
        restart: always
        environment:
            - hapi.fhir.enable_index_missing_fields=true
            - hapi.fhir.auto_create_placeholder_reference_targets=true
            - hapi.fhir.allow_contains_searches=true
            - hapi.fhir.allow_external_references=true
            - hapi.fhir.allow_placeholder_references=true
            - hapi.fhir.default_pretty_print=false
            - hapi.fhir.default_page_size=100       

                
secrets:
  datasource.password:
    file: ./volume/properties/datasource.password  
  common.properties:
    file:  ./volume/properties/common.properties  
  
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.1.0/24  
        
volumes:
  db-data:
  cert-volume:
       
    